---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.kubernetes.additionalLabels }}
  labels:
    control-plane: controller-manager
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.kubernetes.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: punchoperator-controller-manager
  namespace: {{  .Release.Namespace }}
spec:
  replicas: {{ .Values.kubernetes.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- with .Values.kubernetes.additionalLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubernetes.additionalAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 
    spec:
      {{- if .Values.kubernetes.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.kubernetes.imagePullSecret }}
      {{- end }}
      containers:
        - args:
            - --config=controller_manager_config.yaml
          command:
            - /manager
          image: {{ .Values.kubernetes.image }}
          imagePullPolicy: {{ .Values.kubernetes.imagePullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports:
            - containerPort: 8443
              name: metric-server
              protocol: TCP
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: {{ .Values.kubernetes.resources.limits.cpu }}
              memory: {{ .Values.kubernetes.resources.limits.memory }}
            requests:
              cpu: {{ .Values.kubernetes.resources.requests.cpu }}
              memory: {{ .Values.kubernetes.resources.requests.memory }}
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            - mountPath: /controller_manager_config.yaml
              name: manager-config
              subPath: controller_manager_config.yaml
      securityContext:
        runAsNonRoot: true
      serviceAccountName: punchoperator-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
        - configMap:
            name: punchoperator-manager-config
          name: manager-config