apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logInjector.name" . }}
  labels:
    {{- include "logInjector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "logInjector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "logInjector.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{ if .Values.service -}}
          - containerPort: {{ .Values.service.containerPort }}
          {{- end }}
          volumeMounts:
            {{ range $i, $resource := .Values.configMap }}
            - name: {{ $resource.id }}
              mountPath: {{ $resource.dest }}
              subPath: {{ $resource.id }}
            {{- end }}
      volumes:
        {{ range $i, $resource := .Values.configMap }}
        - name: {{ $resource.id }}
          configMap:
            name: {{ $resource.id }}
        {{- end }}