{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "logInjector.name" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.privateRegistryToken }}
{{- end }}