---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: punchoperator-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/punchoperator-serving-cert
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: punchoperator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-punchline-gitlab-thalesdigital-io-v1-flinkline
  failurePolicy: Fail
  name: mflinkline.kb.io
  rules:
  - apiGroups:
    - punchline.gitlab.thalesdigital.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - flinklines
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: punchoperator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-punchline-gitlab-thalesdigital-io-v1-sparkline
  failurePolicy: Fail
  name: msparkline.kb.io
  rules:
  - apiGroups:
    - punchline.gitlab.thalesdigital.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sparklines
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: punchoperator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-punchline-gitlab-thalesdigital-io-v2-batchapplication
  failurePolicy: Fail
  name: mbatchapplication.kb.io
  rules:
  - apiGroups:
    - punchline.gitlab.thalesdigital.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - batchapplications
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: punchoperator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-punchline-gitlab-thalesdigital-io-v2-batchpunchline
  failurePolicy: Fail
  name: mbatchpunchline.kb.io
  rules:
  - apiGroups:
    - punchline.gitlab.thalesdigital.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - batchpunchlines
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: punchoperator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-punchline-gitlab-thalesdigital-io-v2-streamapplication
  failurePolicy: Fail
  name: mstreamapplication.kb.io
  rules:
  - apiGroups:
    - punchline.gitlab.thalesdigital.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - streamapplications
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: punchoperator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-punchline-gitlab-thalesdigital-io-v2-streampunchline
  failurePolicy: Fail
  name: mstreampunchline.kb.io
  rules:
  - apiGroups:
    - punchline.gitlab.thalesdigital.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - streampunchlines
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: punchoperator-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/punchoperator-serving-cert
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: punchoperator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-punchline-gitlab-thalesdigital-io-v1-flinkline
  failurePolicy: Fail
  name: vflinkline.kb.io
  rules:
  - apiGroups:
    - punchline.gitlab.thalesdigital.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - flinklines
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: punchoperator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-punchline-gitlab-thalesdigital-io-v1-sparkline
  failurePolicy: Fail
  name: vsparkline.kb.io
  rules:
  - apiGroups:
    - punchline.gitlab.thalesdigital.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - sparklines
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: punchoperator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-punchline-gitlab-thalesdigital-io-v2-batchapplication
  failurePolicy: Fail
  name: vbatchapplication.kb.io
  rules:
  - apiGroups:
    - punchline.gitlab.thalesdigital.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - DELETE
    - UPDATE
    resources:
    - batchapplications
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: punchoperator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-punchline-gitlab-thalesdigital-io-v2-batchpunchline
  failurePolicy: Fail
  name: vbatchpunchline.kb.io
  rules:
  - apiGroups:
    - punchline.gitlab.thalesdigital.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - DELETE
    - UPDATE
    resources:
    - batchpunchlines
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: punchoperator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-punchline-gitlab-thalesdigital-io-v2-streamapplication
  failurePolicy: Fail
  name: vstreamapplication.kb.io
  rules:
  - apiGroups:
    - punchline.gitlab.thalesdigital.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - DELETE
    - UPDATE
    resources:
    - streamapplications
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: punchoperator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-punchline-gitlab-thalesdigital-io-v2-streampunchline
  failurePolicy: Fail
  name: vstreampunchline.kb.io
  rules:
  - apiGroups:
    - punchline.gitlab.thalesdigital.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - DELETE
    - UPDATE
    resources:
    - streampunchlines
  sideEffects: None
