---
apiVersion: v1
kind: Service
metadata:
  name: punchoperator-metrics-service
  namespace: {{  .Release.Namespace }}
  labels:
    control-plane: controller-manager
spec:
  type: ClusterIP
  ports:
    - name: "8443"
      port: 8443
  selector:
    control-plane: controller-manager