---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "archive-housekeeping.fullname" . }}-config
  labels:
    {{- include "archive-housekeeping.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |
    archiving_pools:
    {{- toYaml .Values.pools | nindent 8 }}
  {{ if .Values.properties }}
  punchplatform.properties: |-
    {{ .Values.properties | nindent 8}}
  {{ end }}