apiVersion: v1
kind: Service
metadata:
  name: {{ include "extraction-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.server.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: extraction-server
