artifacts-server:
  ingress:
    url: artifacts-server.punch
    ingressClassName: ""
  config:
    application:
      tenant: "default"
    metadata: 
      minio:
        host: http://minio.default:9000
        access_key: minioadmin
        secret_key: minioadmin
    data:
      minio:
        host: http://minio.default:9000
        access_key: minioadmin
        secret_key: minioadmin
    keycloak:
      enabled: false

punch-board:
    config:
      punchArtifacts: 'http://artifacts-server.default:4245'
    ingress:
      enabled: true
      className: nginx
      annotations: 
        "nginx.ingress.kubernetes.io/proxy-buffer-size": "128k"
      hosts:
        - host: board.punch
          paths:
            - path: /
              pathType: ImplementationSpecific

minio:
  enabled: true
  fullnameOverride: minio
  replicas: 1
  mode: standalone
  rootUser: minioadmin
  rootPassword: minioadmin
  consoleIngress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - minio.punch
  resources:
    requests:
      cpu: 0
      memory: 0

certmanager:
  enabled: true