artifacts-server:
  ingress:
    url: artifacts-server.punch
  config:
    application:
      tenant: "default"
    metadata: 
      file: /tmp/artifacts/metadata
    data:
      file: /tmp/artifacts/data
    keycloak:
      enabled: false

punch-board:
    config:
      punchArtifacts: 'http://artifacts-server.default:4245'
    ingress:
      enabled: true
      annotations: 
        "nginx.ingress.kubernetes.io/proxy-buffer-size": "128k"
      hosts:
        - host: board.punch
          paths:
            - path: /
              pathType: ImplementationSpecific