---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: artifacts
data:
  application.yml: |
    server:
      port: {{ .Values.server.port }}

    application:
      tenant: {{ .Values.application.tenant }}

    web:
      enabled: {{ .Values.web.enabled }}

    metadata:
    {{- if .Values.metadata.elasticsearch }}
      elasticsearch:
      {{- toYaml .Values.metadata.elasticsearch | nindent 8 }}
    {{- else if .Values.metadata.file }}
      file:
      {{- toYaml .Values.metadata.file | nindent 8 }}
    {{- end }}

    data:
    {{- if .Values.data.minio }}
      minio:
      {{- toYaml .Values.data.minio | nindent 8 }}
    {{- else if .Values.metadata.file }}
      file:
      {{- toYaml .Values.data.file | nindent 8 }}
    {{- end }}

    spring:
    {{- toYaml .Values.spring | nindent 6 }}

    logging:
      level:
        root: INFO
