---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: artifacts
data:
  application.yml: |
    {{- toYaml .Values.config | nindent 4 }}
