---
{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.serviceAccount.name}}
  namespace: {{.Release.Namespace | quote}}
  annotations:
  {{ if .Values.gcpConfig.enabled }}
    iam.gke.io/gcp-service-account: {{.Values.gcpConfig.serviceAccountName }}
  {{ end }}
{{ end }}