---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    ---
    apiVersion: punchoperatorconfig.punchplatform.io/v2
    kind: PunchOperatorConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: :8443
    webhook:
      port: 9443
    leaderElection:
      leaderElect: false
      resourceName: c4b45ab4.gitlab.thalesdigital.io  
    punch:
    {{- with .Values.operator.punch }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-manager-config
  namespace: {{  .Release.Namespace }}