---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-push-service
  namespace: {{  .Release.Namespace }}
  labels:
    control-plane: {{ .Release.Name }}-controller-manager
spec:
  type: ClusterIP
  ports:
    - name: "9898"
      port: 9898
  selector:
    control-plane: {{ .Release.Name }}-controller-manager