---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: punchoperator-serving-cert
  namespace: {{  .Release.Namespace }}
spec:
  dnsNames:
    - punchoperator-webhook-service.{{  .Release.Namespace }}.svc
    - punchoperator-webhook-service.{{  .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: punchoperator-selfsigned-issuer
  secretName: webhook-server-cert