---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webhook-service
  namespace: {{  .Release.Namespace }}
  labels:
    control-plane: {{ .Release.Name }}-controller-manager
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: {{ .Release.Name }}-controller-manager