{{ if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 5g
spec:
  rules:
  - host : {{ .Values.ingress.url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: {{ .Values.server.port }}
  - host: jupypunch.sparkui
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: 4040
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: 8888
{{ end }}