---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    app: datastudio  
  ports:
  - name: http
    port: {{ .Values.server.port }}
    targetPort: {{ .Values.server.port }}
  - name: blockmanager
    port: 7777
    protocol: TCP
  - name: driver
    port: 2222
    protocol: TCP
  - name: spark-ui
    port: 4040
    protocol: TCP