---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}  
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.server.port }}
    targetPort: {{ .Values.server.port }}
  - name: blockmanager
    protocol: TCP
    port: {{ .Values.blockmanager.port }}
    targetPort: {{ .Values.blockmanager.port }}
  - name: driver
    protocol: TCP
    port: {{ .Values.driver.port }}
    targetPort: {{ .Values.driver.port }}
  - name: spark-ui
    protocol: TCP
    port: {{ .Values.spark_ui.port }}
    targetPort: {{ .Values.spark_ui.port }}