image:
  name: ghcr.io/punchplatform/artifacts-server:7.0.1-SNAPSHOT
  secret: admin-secret
  policy: IfNotPresent

server:
  port: 4245

ingress:
  enabled: true
  url: artifacts.dpsc

application:
  tenant: mytenant
  file_size: 100MB

web:
  enabled: true

metadata:
  file: /tmp/artifacts/metadata
data:
  file: /tmp/artifacts/data
