image:
  name: ghcr.io/punchplatform/artifacts-server:8.1-dev
  # -- secret to pull image
  secret: admin-secret
  policy: IfNotPresent

serviceAccount:
  name: default
  create: false

gcpConfig:
  enabled: false
  serviceAccountName: '' #A GKE service account 
  
ingress:
  # -- enable an ingress
  enabled: true
  proxyBodySize: 5g
  # -- ingress url
  url: artifacts-server.dpsc
  # -- ingress class name to select an ingress controller
  ingressClassName: nginx
  ## activate tls to expose ingress with a certificate
  tls: false
  certManagement: cert-manager # can be cert-manager or imported
  #activated when cert_management = cert-manager
  certManager:
    issuerType: cluster-issuer # can be cluster-issuer or issuer
    issuerName: myissuer # issuer name

server:
  port: 4245
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:
      pattern: '%h %l %u %t "%r" %s %b %D'

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    okhttp3: INFO
    com.github.punchplatform.artifacts.server.controllers.utils.ReadWriteLock: DEBUG

env: 
  - name: JDK_JAVA_OPTIONS
    value: "-Xms100m -Xmx450m"

resources: 
  requests:
    memory: 100Mi
  limits:
    memory: 500Mi

config:
  # ---------------------------------
  # Punch Artifact Server configuration file
  # ---------------------------------

  springdoc:
    # /v3/api-docs endpoint
    api-docs:
      path: /v1/api-docs
      enabled: true
    # /swagger-ui.html endpoint
    swagger-ui:
      enabled: true
    # Paths to include
    pathsToMatch:
      - /v1/**
    writer-with-order-by-keys: true

  server:
    # -- port to run the app
    port: 4245

  application:
    # -- tenant to store data
    tenant: mytenant

  # -- spring configuration
  spring:
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB

#  keycloak:
#    # -- Keycloak auth server informations
#    enabled: true
#    realm: master
#    auth-server-url: http://keycloak.punch:8080/
#    resource: artifacts-server
#    credentials:
#      secret: BVl1UNFSONUXjvk7uxkdQyVkiXWKAuIf
#    use-resource-role-mappings: true
#    bearer-only: true

  metadata:
    # -- Connection information for Minio and gcs metadata backend
    type: minio
    minio:
      skipCreateBucket: false
      host: http://s3.object-store:9000
      access_key: minio
      secret_key: password

  data:
    # -- Connection information for Minio and gcs data backend
    type: minio
    minio:
      skipCreateBucket: false
      host: http://s3.object-store:9000
      access_key: minio
      secret_key: password
