image:
  name: ghcr.io/punchplatform/artifacts-server:7.0.1-SNAPSHOT
  secret: admin-secret
  policy: IfNotPresent

server:
  port: 4245

ingress:
  url: artifacts.dpsc
  enabled: true

application:
  tenant: mytenant
  file_size: 100MB

web:
  enabled: true

metadata:
  elasticsearch:
    http_hosts:
      - host: elasticsearch.doc-store
        port: 9200
        scheme: http
    index: artifacts-metadata
    security:
      credentials:
        username: admin
        password: admin
      ssl:
        use_self_signed_certificate: false
        hostname_verification: false
data:
  minio:
    host: http://s3.object-store:9000
    access_key: minio
    secret_key: K@st2020*



