image:
  name: ghcr.io/punchplatform/artifacts-server:8.0-dev
  # -- secret to pull image
  secret: admin-secret
  policy: IfNotPresent

server:
  # -- port to run the app
  port: 4245

ingress:
  # -- enable an ingress
  enabled: true
  # -- ingress url
  url: artifacts-server.dpsc

application:
  # -- tenant to store data
  tenant: mytenant

# -- spring configuration
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

web:
  # -- enable Artifacts Server UI
  enabled: true

metadata:
  # -- ES backend - connection information
  elasticsearch:
    http_hosts:
      - host: elasticsearch.doc-store
        port: 9200
        scheme: http
    index: artifacts-metadata
    security:
      credentials:
        username: admin
        password: admin
      ssl:
        use_self_signed_certificate: false
        hostname_verification: false
  # -- (string) path to folder for FS metadata backend
  file:

data:
  # -- Connection information for Minio data backend
  minio:
    host: http://s3.object-store:9000
    access_key: minio
    secret_key: password
  # -- (string) path to folder for FS data backend
  file:


