image:
  name: ghcr.io/punchplatform/artifacts-server:7.0.1-rc5
  secret: admin-secret
  policy: IfNotPresent

server:
  port: 4245

ingress:
  url: artifacts.dpsc
  enabled: true

application:
  tenant: mytenant
  file_size: 100MB

web:
  enabled: true

metadata:
  elasticsearch:
    hosts:
      - http://elasticsearch.doc-store:9200
    index_name: artifacts-metadata

data:
  minio:
    host: http://s3.object-store:9000
    access_key: minio
    secret_key: K@st2020*



