image:
  name: ghcr.io/punchplatform/artifacts-server:8.1-dev
  # -- secret to pull image
  secret: admin-secret
  policy: IfNotPresent

ingress:
  # -- enable an ingress
  enabled: true
  # -- ingress url
  url: artifacts-server.dpsc
  # -- ingress class name to select an ingress controller
  ingressClassName: nginx
  ## activate tls to expose ingress with a certificate
  tls: false
  certManagement: cert-manager # can be cert-manager or imported
  #activated when cert_management = cert-manager
  certManager:
    issuerType: cluster-issuer # can be cluster-issuer or issuer
    issuerName: myissuer # issuer name

server:
  # -- port to run the app
  port: 4245

config:
  # ---------------------------------
  # Punch Artifact Server configuration file
  # ---------------------------------

  server:
    # -- port to run the app
    port: 4245

  application:
    # -- tenant to store data
    tenant: mytenant

  # -- spring configuration
  spring:
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB

  web:
    # -- enable Artifacts Server UI
    enabled: false

  security:
    # -- enable Artifacts Server security with keycloak
    enabled: false

  keycloak:
    # -- Keycloak auth server informations
    auth_server_url: http://keycloak-http.authentication/auth/
    realm: kast
    resource: artifact-server
    public_client: true
    principal_attribute: preferred_username
    use_resource_role_mappings: true

  metadata:
    # -- Connection information for Minio metadata backend
    minio:
      host: http://s3.object-store:9000
      access_key: minio
      secret_key: password

  data:
    # -- Connection information for Minio data backend
    minio:
      host: http://s3.object-store:9000
      access_key: minio
      secret_key: password
